name: CI

on:
  pull_request:
  push:
    branches-ignore: [master]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-java@v2
      with:
        distribution: temurin
        java-version: 17
    - uses: actions/setup-sbt@v1
    - name: Compile
      run: sbt clean +testables/test versionPolicyCheck

