name: CI

on:
  pull_request:
  push:
    branches-ignore: [master]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - uses: olafurpg/setup-scala@v10
    - name: Compile
      run: sbt clean +testables/test versionPolicyCheck

