name: CI

on:
  pull_request:
  push:
    branches-ignore: [master]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - uses: olafurpg/setup-scala@v10
    - name: Compile
      run: sbt clean +testables/test
    - name: Codecov
      uses: codecov/codecov-action@v1.0.2
      with:
        token: ${{secrets.CODECOV_TOKEN}}

