name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - uses: olafurpg/setup-scala@v2
    - name: Compile
      run: sbt clean compile clean coverage testables/test coverageAggregate
    - name: Codecov
      uses: codecov/codecov-action@v1.0.2
      with:
        token: ${{secrets.CODECOV_TOKEN}}

